# Generated by Django 5.0.3 on 2024-06-16 12:47

import django.core.validators
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_comment_file_comment_image_alter_comment_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=post.models.upload_image_file
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=post.models.upload_image_file
            ),
        ),
    ]
